ja: updated translation of Obsidian Sync & Mobile apps
obsidianmd/obsidian-docs pull request #156
Opened 2021-07-17 04:06 UTC by yo-goto

2021-07-17 05:39 UTC, taksas requested changes
いくつかの変更の提案をします。

2021-07-17 05:39 UTC, taksas commented on ja/ライセンスとアドオンサービス/Obsidian Sync.md
> +｢設定｣ → ｢同期｣ → ｢選択的同期｣から画像、音声、動画、PDFとサポートされていないファイルの同期を行うかどうかを選択できます。
「ファイルの同期を行うかどうかを選択できます」→「ファイルの同期を行うかどうかの切り替えができます」
のほうがいいと思います。(ja.termbase.mdより)
原文：You can toggle sync for images, audio, video, PDFs, and unsupported files under Settings -> Sync -> Selective sync.

2021-07-17 05:39 UTC, taksas commented on ja/ライセンスとアドオンサービス/Obsidian Sync.md
> +何かしらのエラーが発生して設定の一部を損失してしまった場合には、同期プラグインの｢設定のバージョン履歴｣項目から影響を受けた設定をいつでも復帰させることが可能です。
「いつでも復帰させることが可能です」→「いつでも元に戻すことが可能です」のほうがいいと思います。
原文：you can always revert the affected settings file through the "Settings version history" section in Sync.

2021-07-17 05:39 UTC, taksas commented on ja/Obsidian/ベータ版モバイルアプリ.md
> +#insider-build-mobile チャンネルに進み、ピン留めされたメッセージを開いてモバイルアプリのインストール手順を確認しください。
「インストール手順を確認しください」→「インストール手順を確認してください」

2021-07-17 05:39 UTC, taksas commented on ja/Obsidian/iOSアプリ.md
> +現在、ObsidianはFileProviderを介して仮想ファイルシステムを提供するサードパーティの同期サービスプロバイダーに対しての直接的なサポートは行っていませんが、将来的には機能向上としてこの問題に試みる予定です。
「この問題に試みる予定です」→「この問題の解決を試みる予定です」の方がいいと思います。

2021-07-17 05:39 UTC, taksas commented on ja/Obsidian/Androidアプリ.md
> +Android版アプリは現在パブリックリリースとして公式に利用可能です。 https://obsidian.md/mobile からPlayストアのリンクにアクセスできます。
「現在パブリックリリースとして公式に利用可能です。https～」→「現在一般に公開されており、https～」の方がいいと思います。
原文：The Android app is now publicly available, and a link to the Play store listing can be found at https://obsidian.md/mobile

2021-07-17 05:39 UTC, taksas commented on ja/Obsidian/iOSアプリ.md
> +iOS版アプリは現在パブリックリリースとして公式に利用可能です。 https://obsidian.md/mobile からAppストアのリンクにアクセスできます。
「現在パブリックリリースとして公式に利用可能です。https～」→「現在一般に公開されており、https～」の方がいいと思います。
原文：The iOS app is now publicly available, and a link to the app store listing can be found at https://obsidian.md/mobile

2021-07-17 06:30 UTC, yo-goto commented
レビューありがとうございます。修正しました!

2021-07-17 07:03 UTC, taksas requested changes
すみません、もう一点ありました。修正お願いします。

2021-07-17 07:03 UTC, taksas commented on ja/ライセンスとアドオンサービス/Obsidian Sync.md
> +ノートと添付ファイルの同期に加えて、Obsidian Syncでは以下のファイについての独立した同期方法を提供しています。
「以下のファイについて」→「以下のファイルについて」

2021-07-17 07:14 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Sync.md
> +ノートと添付ファイルの同期に加えて、Obsidian Syncでは以下のファイについての独立した同期方法を提供しています。
指摘ありがとうございます。OKです

2021-07-17 07:16 UTC, taksas approved these changes
修正ありがとうございました。

2021-07-17 07:21 UTC, yo-goto commented
@ericaxu It's ready to be merged. Please update online Ja help docs after merging cause everyone want to  know how to use Obsidian mobile and how to sync data.

2021-07-24 00:08 UTC, yo-goto commented
hey @ericaxu, please merge this PR and update online docs 😅

2021-07-24 08:13 UTC, ericaxu commented
Thank you for your work! <3

2021-07-24 08:13 UTC, merged