ja: various update
obsidianmd/obsidian-docs pull request #167
Opened 2021-07-26 14:29 UTC by yo-goto

2021-07-27 00:00 UTC, taksas requested changes

2021-07-27 00:00 UTC, taksas commented on ja/プラグイン/Zettelkastenプレフィクサー.md
> +For the Zettelkasten prefixer plugin, `{{date}}` and `{{time}}` do not work. Please use `{{date:YYYY-MM-DD}}` and `{{time:HH:mm}}` in your template.
翻訳をよろしくお願いします。

2021-07-27 10:12 UTC, yo-goto commented on ja/プラグイン/Zettelkastenプレフィクサー.md
> +For the Zettelkasten prefixer plugin, `{{date}}` and `{{time}}` do not work. Please use `{{date:YYYY-MM-DD}}` and `{{time:HH:mm}}` in your template.
その部分消し忘れてました！

2021-07-27 14:51 UTC, yo-goto commented
修正+新規追加しました

2021-07-27 14:57 UTC, taksas approved these changes
修正ありがとうございました。

2021-07-27 16:09 UTC, yo-goto commented
Ready to be merged.

2021-07-29 03:58 UTC, ericaxu commented
Thank you for your work! <3

2021-07-29 03:58 UTC, merged