0.12.12 YAML support for Publish
obsidianmd/obsidian-docs pull request #180
Opened 2021-08-14 14:43 UTC by leah-ferguson

Added information for YAML keys added in 0.12.12

2021-08-14 14:49 UTC, kometenstaub requested changes

2021-08-14 14:49 UTC, kometenstaub commented on en/Plugins/Publish.md
> +If you set `publish: false`, then the file will not be visble when publishing changes, and will not show up in new/changed files. If this file had been previously published, you will see an option to
There's a typo in the last word.

2021-08-14 14:51 UTC, leah-ferguson commented on en/Plugins/Publish.md
> +If you set `publish: false`, then the file will not be visble when publishing changes, and will not show up in new/changed files. If this file had been previously published, you will see an option to
Thanks!

2021-08-14 15:04 UTC, kometenstaub approved these changes
:+1:

2021-08-16 03:57 UTC, ericaxu commented
Thank you for your amazing work!

2021-08-16 03:57 UTC, merged