ja: small update
obsidianmd/obsidian-docs pull request #184
Opened 2021-09-01 15:28 UTC by hnsol

fixed typo and corrected small mistakes

2021-09-04 01:59 UTC, yo-goto requested changes
レビューでいくつかの修正を提案しました。

2021-09-04 01:59 UTC, yo-goto commented on ja/Obsidian/iOSアプリ.md
> -iCloudでの同期を行わない場合には、保管庫はObsidianアプリのサンドボックスファイルシステムに保存されます。ローカル保管庫はファイルシステムを介したフォルダ選択をサポートしている他のアプリからアクセスできます。例えば、Working CopyのようなアプリはObsidianのローカル保管庫の同期に使用できます。
｢使う、使わない｣の表現だと分かりづらいので前の｢同期を行う･行わない｣という表現の方がいいと思います。

2021-09-04 01:59 UTC, yo-goto commented on ja/Obsidian/iOSアプリ.md
> +ひとつの選択肢として、iCloud Driveへ保管庫を保存することができます。その場合、保管庫はiCloud Driveフォルダのなかの、"Obsidian"という名前のフォルダの下に置かれます。フォルダにはObsidianのロゴが表示されています。
｢一つの｣、｢中の｣

2021-09-04 01:59 UTC, yo-goto commented on ja/Obsidian/iOSアプリ.md
> +または、Gitを使用してiOSの保管庫を同期するようWorkingCopyを設定することもできます。これを行うためには、まず最初にデバイス上に空のローカル保管庫を作成する必要があります。次に、｢フォルダー同期のセットアップ｣を行い、Obsidianのアプリ内部のローカル保管庫を選択してください。これによって、手動でコミットとプッシュが可能になります。
Working Copyは別のアプリなので、
｢Working Copyを利用することができます｣という表現の方がよいと思います。

2021-09-04 01:59 UTC, yo-goto commented on ja/Obsidian/iOSアプリ.md
> +1WriterやiA Writerといった他のアプリと異なるObsidianの特徴は、単一のノートではなく保管庫の上で機能しているということです。リンクの自動補完、画像の埋め込み、タグペイン、バックリンク、すべてのクロスノート機能など、Obsidianのコア機能の多くは、保管庫全体とその内部のすべてのファイルに依存しています。
｢保管庫の上｣→｢保管庫のトップ｣
日本語の上だと｢単一ファイルの上層レイヤーということが｣分かりづらいのでトップの方がよいと思います。

2021-09-05 14:15 UTC, hnsol commented on ja/Obsidian/iOSアプリ.md
> +iOS版アプリが公開されました。 https://obsidian.md/mobile からAppストアのリンクにアクセスできます。
レビューありがとうございました。よく理解いたしました。

2021-09-05 14:15 UTC, hnsol commented on ja/Obsidian/iOSアプリ.md
> +6. iCloudがモバイルデバイスにすべてを同期するのを待つ
了解いたしました。

2021-09-05 14:16 UTC, hnsol commented on ja/Obsidian/iOSアプリ.md
> -iCloudでの同期を行わない場合には、保管庫はObsidianアプリのサンドボックスファイルシステムに保存されます。ローカル保管庫はファイルシステムを介したフォルダ選択をサポートしている他のアプリからアクセスできます。例えば、Working CopyのようなアプリはObsidianのローカル保管庫の同期に使用できます。
了解いたしました。

2021-09-05 14:17 UTC, hnsol commented on ja/Obsidian/iOSアプリ.md
> +ひとつの選択肢として、iCloud Driveへ保管庫を保存することができます。その場合、保管庫はiCloud Driveフォルダのなかの、"Obsidian"という名前のフォルダの下に置かれます。フォルダにはObsidianのロゴが表示されています。
了解いたしました。対応しました。

2021-09-05 14:17 UTC, hnsol commented on ja/Obsidian/iOSアプリ.md
> +または、Gitを使用してiOSの保管庫を同期するようWorkingCopyを設定することもできます。これを行うためには、まず最初にデバイス上に空のローカル保管庫を作成する必要があります。次に、｢フォルダー同期のセットアップ｣を行い、Obsidianのアプリ内部のローカル保管庫を選択してください。これによって、手動でコミットとプッシュが可能になります。
了解しました。対応しました。

2021-09-05 14:18 UTC, hnsol commented on ja/Obsidian/iOSアプリ.md
> +1WriterやiA Writerといった他のアプリと異なるObsidianの特徴は、単一のノートではなく保管庫の上で機能しているということです。リンクの自動補完、画像の埋め込み、タグペイン、バックリンク、すべてのクロスノート機能など、Obsidianのコア機能の多くは、保管庫全体とその内部のすべてのファイルに依存しています。
了解しました。対応しました。

2021-09-11 15:33 UTC, yo-goto approved these changes
返信おそくなりました。修正ありがとうございました。
レビューコメントで指摘した部分について｢こちらの表現の方がよい｣というところがあればどんどん反論してもらって議論しましょう。

2021-09-12 13:39 UTC, hnsol commented
> 返信おそくなりました。修正ありがとうございました😊
> 今後レビューコメントで指摘する部分について｢こちらの表現の方がよい｣というところがあればどんどん反論してもらって議論していきましょう👍

あたたかいご配慮ありがとうございます。ご指摘いただいた点につきましては、いずれもかなり検討し、よりよいアイディアをおもいつけなかったので、そわせていただきました。今後はさらにフランクに議論させていただければ幸いです🙏

ここまで訳出がすすんでいますので、日本語Obsidianコミュニティに貢献するために、どうすればお役立ちできるか（可読性向上なのか／どの部分に手入れすると価値が大きいのかなど）、じぶんなりに考えながらぼちぼち進めていければとおもっております😌

2021-09-16 07:33 UTC, ericaxu commented
Hi all, is this ready to merge? Thanks.

2021-09-16 08:26 UTC, hnsol commented
> Hi all, is this ready to merge? Thanks.

Ready to merge. Thanks.

2021-09-16 22:02 UTC, ericaxu commented
Thank you for your work! <3

2021-09-16 22:02 UTC, merged