More formatting examples, small rewordings
obsidianmd/obsidian-docs pull request #270
Opened 2022-08-08 13:28 UTC by joethei

~ Adding callout examples as per <https://forum.obsidian.md/t/add-callout-examples-with-colours-to-the-online-help/40725>
~ closing #266 by making the wording clearer and adding examples
~ closing #267 as the changes there are included in this PR
+ More examples

Documenting some syntax that leads to questions in discord sometimes
+ alternative heading syntax
+ loose lists

2022-09-05 15:02 UTC, marcusolsson requested changes

2022-09-08 16:34 UTC, joethei commented on en/How to/Format your notes.md
> +To render math from LaTeX notion Obsidian uses [MathJax](http://docs.mathjax.org/en/latest/basic/mathjax.html).
typo: should be notation

2022-09-10 18:54 UTC, ericaxu commented
There seems to be some conflicts. Let me know when it's ready to merge @joethei @marcusolsson

2022-09-13 08:51 UTC, marcusolsson commented on en/How to/Use callouts.md
> +The syntax has been chosen because:
```suggestion
We choose the syntax because:

```

2022-09-13 08:51 UTC, marcusolsson commented on en/How to/Use callouts.md
> +- it gracefully falls back to blockquotes in unsuported markdown renderers
```suggestion
- it falls back to blockquotes in unsupported markdown renderers
```

2022-09-13 08:51 UTC, marcusolsson commented on en/How to/Use callouts.md
> +- it parses all markdown, including links, embeds, etc.
```suggestion
- it parses all Markdown, including links, embeds, etc.
```

2022-09-13 08:51 UTC, marcusolsson commented on en/How to/Use callouts.md
> +- [[Internal link|Internal link's]] are recognized and will show up in [[Backlinks]], [[Outgoing links]] and [[Graph view]]
```suggestion
- it recognizes [[Internal link|Internal link's]] and will shows up in [[Backlinks]], [[Outgoing links]], and [[Graph view]]
```

2022-09-13 11:21 UTC, marcusolsson approved these changes

2022-09-15 00:04 UTC, ericaxu commented
Thanks all! ❤️

2022-09-15 00:04 UTC, merged