Make clearer where default search operates.
obsidianmd/obsidian-docs pull request #417
Opened 2023-03-09 16:10 UTC by WhiteNoiseDev

State where default Search operates and which operator affect it behavior

2023-03-15 16:05 UTC, ericaxu commented
Thanks for the PR! Could be a little wordy, can you take a look @marcusolsson ?

2023-03-20 14:30 UTC, marcusolsson reviewed
Reading this, it looks like you can't search within, for examples, CSV files, unless you use `file:` or `path:` to include it? Am I correct?

2023-03-20 14:30 UTC, marcusolsson commented on en/Plugins/Search.md
> +A search term is the word or phrase that you enter in the search field. Learning how to write search terms effectively can help you quickly find what you're looking for, even in large vaults. By defa
```suggestion
A search term is the word or phrase that you enter in the search field. Learning how to write search terms effectively can help you quickly find what you're looking for, even in large vaults. By default, Obsidian only searches notes and canvases, including their filenames.
```

According to the [style guide](https://help.obsidian.md/Contributing+to+Obsidian/Style+guide#Notes%2C+files%2C+and+folders), "note" implies Markdown.

2023-03-20 18:05 UTC, WhiteNoiseDev commented
> Reading this, it looks like you can't search within, for example, CSV files, unless you use `file:` or `path:` to include it? Am I correct?

You are wrong.

You can only search within notes and canvases. You can NEVER search within any other file type. 
`File:` and `path:` limit the search to filename and file path, respectively, of all files (beyond notes and canvases) but NOT their content.

2023-03-20 20:47 UTC, marcusolsson commented
> You can NEVER search **within** any other file type

The "By default" in the following sentence seems to suggest that you can? If you can't search other files, then I think we should remove it.

> By default, the search is performed only over all markdown notes and canvases

2023-03-20 22:42 UTC, WhiteNoiseDev commented
You can search other file types, their name not their content.

2023-03-20 23:12 UTC, WhiteNoiseDev commented
The "by default part" can be replaced with "without search operators"

2023-03-21 02:27 UTC, ericaxu commented
> State where default Search operates and which operator affect it behavior

I feel like the goal of this PR seems to be to address some kind of concern. I wonder if it would be easier if you file that as an issue instead and let Marcus figure out a way to fix that? Would you prefer that @marcusolsson ?

2023-03-21 18:55 UTC, marcusolsson commented
I think I understand know:

- You **cannot** search the contents of files other than notes and canvases.
- By default, you **cannot** search the filenames of files other than notes and canvases.
- If you use the `path` and `file` operators, you **can** search the filenames of files other than notes and canvases.

I can see how this would be confusing, so I think we should document it. 

How about this then?:

1. Update the first text to:

   > Obsidian only searches the contents of notes and canvases.

2. Add a callout that explains this explicitly:
   
   ```plain
   > [!tip] Searching paths and filenames
   > By default, you can only search the paths and filenames of notes and canvases. To search for a path or filename of any file in the vault, use the `path` or `file` operator.
   ```

2. I'm on the fence whether the text in the reference table is needed. If you still think it is with the suggestions above, I'd at least refrain from using passive voice:

   > Find text in filename. Matches any file in the vault.

2023-03-23 16:45 UTC, WhiteNoiseDev commented
ok, I would keep all 3 points.

2023-04-25 16:03 UTC, marcusolsson requested changes

2023-04-25 16:03 UTC, marcusolsson commented on en/Plugins/Search.md
> +A search term is the word or phrase that you enter in the search field. Learning how to write search terms effectively can help you quickly find what you're looking for, even in large vaults. By defa
```suggestion
A search term is the word or phrase that you enter in the search field. Learning how to write search terms effectively can help you quickly find what you're looking for, even in large vaults. Obsidian only searches the contents of notes and canvases.

> [!tip] Searching paths and filenames
> By default, you can only search the paths and filenames of notes and canvases. To search for a path or filename of any file in the vault, use the `path` or `file` operator.
```

2023-04-25 16:03 UTC, marcusolsson commented on en/Plugins/Search.md
> +| `file:`         | Find text in filename. All files in the vault are considered.<p/>Example: `file:.jpg` or `file:202209`.
```suggestion
| `file:`         | Find text in filename. Matches any file in the vault.<p/>Example: `file:.jpg` or `file:202209`.                                                                                                                                                     |
```

2023-04-25 16:03 UTC, marcusolsson commented on en/Plugins/Search.md
> +| `path:`         | Find text in file path. All files in the vault are considered.<p/>Example: `path:"Daily notes/2022-07"`.
```suggestion
| `path:`         | Find text in file path. Matches any file in the vault.<p/>Example: `path:"Daily notes/2022-07"`.                                                                                                                                                    |
```

2023-04-25 16:04 UTC, merged