Translate
obsidianmd/obsidian-docs pull request #86
Opened 2021-04-18 06:59 UTC by taksas

2021-04-18 14:37 UTC, yo-goto requested changes
現在、[ja.termbase.md](https://github.com/obsidianmd/obsidian-translations/blob/master/ja.termbase.md)にて表記ルールを定め、UIとドキュメントの整合性を保っているので、参照してください。ルールや用語対応などについてはなるべく協議したいと思います。
Discordの日本語チャンネルがあるのでそちらで会話するか、ルール改定を行う場合にはtermbaseへの追記を行って頂きたいです。

2021-04-18 14:37 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Sync.md
> +1ヶ月以内にサブスクリプションを更新する場合、利用に関する影響はありません。
この場合は｢限り｣が適正だと思います。

2021-04-18 14:37 UTC, yo-goto commented on ja/Obsidian/Obsidianモバイル.md
> +Obsidianが1WriterやiA Writerといった他のアプリと異なる部分の一つとしては、単一のノートというよりはむしろ保管庫のトップで機能するということが挙げられます。オートコンプリートや画像埋め込み、タグペイン、バックリンク、そしてすべてのノート間機能などのObsidianが有するコア機能の多くは、保管庫全体とその内部に存在する全てのファイルに依存しているからです。
｢全て｣→｢すべて｣で協議。

2021-04-18 14:37 UTC, yo-goto commented on ja/Obsidian/Obsidianモバイル.md
> +標準的なマークダウンエディタのアプリでは、同期のために「選択したファイルを開いた際にファイルをダウンロード」と「保存を行った際にファイルをアップロードして戻す」という基本機能を実装しているのみとなっています。Obsidianでは利便性と共に、変更があった全ファイル(例えば、ファイルのリネームを実行した際には、他のファイルに存在するリンク名が変更されるためにそれら一連のファイルを更新するなどの可能
｢｣はUIとドキュメント両方で半角に統一されています。

2021-04-18 14:37 UTC, yo-goto commented on ja/Obsidian/インデックス.md
> +[[クレジット]]ページではObsidianの完成を可能にした全ての驚くべきメンバーをリストしています。
｢全て｣→｢すべて｣で協議。

2021-04-18 14:37 UTC, yo-goto commented on ja/Obsidian/クレジット.md
> +- yo-goto, ぱだわん, taksas (Japanese)
名前を新規追加し、アルファベット順にソートしてください。

2021-04-18 14:37 UTC, yo-goto commented on ja/Obsidian/ベータ版モバイルアプリ.md
> +数週間のアプリの安定化作業が終わり次第、カタリストインサイダーに提供を開始し、その後全ての方に提供する予定となっています。
｢全て｣→｢すべて｣で協議。

2021-04-18 14:37 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +[[パブリッシュ|パブリッシュプラグイン]]を介して公開するものについては保管庫全体を公開するか、保管庫内の選択したノートのみを公開するか、ユーザーによって完全にコントロールされます。**公開しないように**選択した全てのノートについて、それらのノートは完全にプライベートであり、Obsidian Publishはその内容についてまったく感知しないことに確信を持つことができます。
｢全て｣→｢すべて｣で協議。

2021-04-18 14:37 UTC, yo-goto commented on ja/ガイド/キーボードショートカット.md
> +他の全てのペインを閉じる           |   | ブランク
｢全て｣→｢すべて｣で協議。

2021-04-18 14:37 UTC, yo-goto commented on ja/ガイド/ノートの名前を変更する.md
> +既にノートを編集している場合は、タイトルのテキストを編集するだけで名前を変更できます。
｢既に｣→｢すでに｣で統一してください。

2021-04-18 15:43 UTC, yo-goto requested changes
主に副詞のひらがな表記は変えないようにしてください。
｢全て｣→｢すべて｣
｢既に｣→｢すでに｣

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/ノートをフォーマットする.md
> +Obsidianはマークダウンベースのノートテイキングアプリであり、ナレッジベースのアプリでもあります。
｢ノートテイキングアプリ｣と｢ナレッジベースアプリ｣で対にするので、｢の｣はない方がよいと思います。

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/ノートをフォーマットする.md
> +    タブでインデントされていたテキストはこのようにフォーマットされ、プレビューモードではコードブロックのように表示されます。
｢インデントされていた｣→｢インデントされた｣

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/カスタムスタイルの追加.md
> +2. ｢設定｣ → ｢外観｣ → ｢テーマ｣内のドロップダウンメニューから好きなテーマを有効化できます。
｢｣→｢｣内の~
という表現は分かりづらいので｢~へと進み、｣にしてください。

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/テキストのフォールド.md
> +Obsidianはマークダウン形式の見出しやインデントされたリストの両方を折りたたむことが可能です。このノートの下向きの矢印がタイトルの隣にあることに注意してください。クリックした場合、全てのノートをフォールドします。クリックするとノートを再び表示します。これはリスト内のインデントによる多数のレベルと同様に、マークダウンの複数のレベルでも適応されます。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/バックリンクの扱い.md
> +バックリンクはObsidianの最も強力な機能の一つです。その分利用者がしばしば混乱してしまう可能性があるので、ここにそんなときに役立つと思われるいくつかのことがらを書き記しておきます。
原文: confusing
利用者をしばしば混乱させてしまう可能性があるので

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/バックリンクの扱い.md
> +このドキュメントから見えるように、現在、各セクションには一つずつエントリーがあります。リンクされたメンションでは、このドキュメントに対して[[リンクされたペイン]]のノートで作成したリンクが表示されているはずです。しかし、リンクされていないメンションでもリンクを見ることができます。それは他のドキュメントでノート名は書いてはいますが明示的なリンクにはなっていないからです。
元のままでお願いします。

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/複数の保管庫での作業.md
｢Nested Vault: ネストされた保管庫｣はForum上によくあがる話題であり、公式からも言及されるため、あえて｢ネストされた保管庫｣として注意を引く意味でもこの表記にしています。

2021-04-18 15:43 UTC, yo-goto commented on ja/ガイド/複数の保管庫での作業.md
> +テーマやプラグインなどのすべての設定は保管庫のディレクトリ直下の `.obsidian` フォルダのに保存されています。このフォルダを保管庫から別の保管庫へコピーすると、すべての設定が複製されます。全ての設定を有効化させるにはObsidianを再起動する必要があるかもしれません。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/グラフビュー.md
> +- 各ノードにカーソルを合わせることで連結をハイライトし、他のノード全てを暗くします。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/コマンドパレット.md
> +コマンドパレットはキーストロークを覚える必要なく、Obsidianのほぼ全ての機能へアクセスできる非常に便利な方法なので、このプラグインはデフォルトで有効になっています。`Ctrl/Cmd+P` を入力してコマンドパレットをアクティブにし、コマンド名を入力してください。コマンドにホットキーがある場合には右側に表示されます。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/コマンドパレット.md
> +- ショートカットと共に全てのコマンドのリストのを見るには、プロンプトで何も入力せずに、矢印キーを使ってリストを移動してください。`Return` キーでコマンドをアクティブにできます。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/タグペイン.md
> +利用している全てのタグをタグカウントと共に表示するパネルを右側に追加できます。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/テンプレート.md
> +テンプレートの各スニペットはObsidianの他の全てと同じように単なる普通のマークダウンノートです。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/テンプレート.md
> +全てのテンプレートファイルで機能する `{{date}}` と `{{time}}` に加えて、 一度だけ特定のフォーマットで挿入したいという場合に `{{date:YYYY-MM-DD}}` フォーマットを利用することできます。これは、`{{date}}` フォーマットをオーバーライドします。`:`の後に続く文字は日付フォーマット部分として扱われます。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/パブリッシュ.md
> +パブリッシュプラグインを使えば、保管庫からサイトへのノートの公開を全てObsidianのアプリ内で行うことができます。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/パブリッシュ.md
> +既に公開されているノートの内容を変更した際には、パブリッシュプラグインのダイアログを開くと変更のあるノートが自動的に選択されます。サイトに公開したくないファイルは全て対象外にできます。
｢既に｣→｢すでに｣で統一してください。

2021-04-18 15:43 UTC, yo-goto commented on ja/プラグイン/検索.md
> +	- 例えば、`foo OR bar` で検索するとそれらの単語のいずれかを含むような全てのノートが検索されますが、その場合は同一のノートに両方の単語が含まれる必要はありません。`foo -bar` で検索すると `foo` を含むが、`bar` を含むものは除外されるように検索されます。
｢全て｣→｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +このオプションを有効にすると、ナビゲーションサイドバーにサイト内の全ての公開ページとフォルダが表示されるようになります。閲覧者が現在開いているノートがハイライトされ、クリックすることで他のノートへ移動できます。
すべて

2021-04-18 15:43 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +このオプションを有効化すると、Google等の検索エンジンがサイトのインデックスを作成しないようにサイト内の全てのページにインデックス化無効のメタタグを追加します。このオプションを使用していなくても、パスワードによってサイトが保護されている場合でも検索エンジンはインデックスを作成できないこと注意してください。
｢このオプションを使用していなくても｣はいらないです。

2021-04-18 15:43 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +ユーザー自身のウェブサーバーをホストし、独自のSSL暗号化をセットアップしたい場合には、このオプションを選択してください。既に所有しているドメインやサブドメイン下でウェブサイトをホストしている場合には、サイト全体をホストする代わりに特定のURLパス下でObsidian Publishによるサイトをロードするためにこのオプションを利用し、ウェブサイトをセットアップしてください。
｢すでに｣に統一してください。

2021-04-18 15:43 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +そのURLパスの元にある全てのリクエストを`https://publish.obsidian.md/serve?url=my-domain.com/my-subpath/...` に対してプロキシし、Obsidianにて同一のURLパスに対してサイトオプションの設定を行ってください。
｢すべて｣

2021-04-18 15:43 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +カスタムドメインを設定した後、以前の `https://publish.obsidian.md/slug` リンクからサイトに訪問した場合には、正確にサイトを読み込めるように特定の項目(フォント、グラフ、パスワード等)に関するブラウザのキャッシュを消去する必要があるかもしれません。これはモダンなブラウザによって課されるクロスドメインのセキュリティ上の制限のためです。サイト閲覧者に対してカスタムド
｢限って｣で大丈夫です。

2021-04-18 15:43 UTC, yo-goto commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +- 訪問者がサイトを表示するとき、データの上限を超えないようにするために役立つ高効率のビデオ圧縮。
体言止め→上下の表現に合わせてください。

2021-04-19 08:08 UTC, yo-goto requested changes
あと少しだけ修正をお願いします。僕の方で出したプルリクエストは一旦取り下げるので、このプルリクエストが承認された後にマージのコンフリクト処理を僕が行い、再びプルリクエストを作成します。

2021-04-19 08:08 UTC, yo-goto commented on ja/プラグイン/パブリッシュ.md
> +｢リンクされているファイルを追加｣ボタンは、現在公開するように選択している全てのノートから参照されている(リンクされている)保管庫内の全ノートを含めて公開するオプションです。これは公開しているサイトにおいて、すべてのリンクが有効になります。
｢すべて｣

2021-04-19 08:08 UTC, yo-goto commented on ja/ガイド/カスタムスタイルの追加.md
> +CSSスニペットは変更や追加したいものに関しての小さく断片的なCSSとして想定されています。これらのスニペットは表示されているディレクトリに置かれる必要があります。
｢小さく断片的なCSSファイルとして想定｣の方が良さそうです。

2021-04-19 09:03 UTC, taksas commented
何度もご指摘ありがとうございます。

2021-04-19 09:22 UTC, yo-goto approved these changes
修正ありがとうございました!!
一人でやっていると誤字脱字誤訳に気づけないので今後もご協力お願いできると嬉しいです。

2021-04-19 19:35 UTC, ericaxu commented
Hi there,

Is this ready to be merged or are you going to fix more translations? Thanks!

2021-04-19 22:31 UTC, taksas commented
Hi,
This is ready to be marged.
I wanna keep being a japanese translator,so best regards from now on!

2021-04-21 05:15 UTC, yo-goto commented
Hey, @ericaxu. It's OK. Please merge this pull request. 
I've already reviewed and checked. It's been ready to be merged.
After that, I'll submit another pull request to resolve conflicts and patch translation.

2021-04-26 17:10 UTC, ericaxu commented
Sounds good, thanks so much @taksas @yo-goto !

2021-04-26 17:10 UTC, merged