ja: Up-to-date as of 2021-04-27
obsidianmd/obsidian-docs pull request #94
Opened 2021-04-27 03:29 UTC by yo-goto

- everything is up-to-date
- handled conflicts with the previous Japanese translation pull request
- fixed minor mistakes and notation rules

2021-04-27 06:07 UTC, taksas requested changes
各部分に小さな変更を提案します。

2021-04-27 06:07 UTC, taksas commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +2. DNSへと進み｢レコードの追加(Add Record)｣をクリックしてください。｢タイプ(Type)｣でCNAMEを選択し、｢名前(name)｣の項目に追加したいドメインかサブドメイン(例: n`otes.mysite.com`)を入力してください。｢ターゲット(target)｣に対して、値 `publish-main.obsidian.md` を入力してください。入力の際に、この値に個人
「　サブドメイン(例: n`otes.mysite.com`)　」の部分で、「`」の位置がずれています。

2021-04-27 06:07 UTC, taksas commented on ja/ライセンスとアドオンサービス/Obsidian Publish.md
> +- 高効率な映像圧縮によって、訪問者がサイト閲覧時にデータ上限を越さないように保証します。
「越さないように」ではなく「超さないように」の方が適切だと思います。

2021-04-27 06:07 UTC, taksas commented on ja/ライセンスとアドオンサービス/Obsidian Sync.md
> +サードパーティの同期サービスを利用して保管庫のバックアップを保持したい場合には、主要な単一のデバイス上で同期サービスプロバイダーをセットアップすることで依然としてそれ実現できます。しかし、2つ目のデバイス上ではできません。これによってサードパーティの同期サービスがObsidian Syncと競合しないように保証できます。
「それ実現できます」→「それを実現できます」だと思います。

2021-04-27 07:36 UTC, yo-goto commented on ja/Obsidian/Obsidianモバイル.md
> +下に示したように、Androidでの同期と同様のステップに従うことで同期できます。現在、Obsidian Syncによる同期とiCloudによる同期の両方を同時に使用することは推奨していません。同時使用によって競合状態によるデータロスの発生が報告されています。
検索数図ったらたしかにデータロストの方が多かったです。変更します

2021-04-27 07:37 UTC, yo-goto commented
ありがとうございます! 後で修正しておきます。

2021-04-27 07:49 UTC, yo-goto commented on ja/Obsidian/Obsidianモバイル.md
> +下に示したように、Androidでの同期と同様のステップに従うことで同期できます。現在、Obsidian Syncによる同期とiCloudによる同期の両方を同時に使用することは推奨していません。同時使用によって競合状態によるデータロスの発生が報告されています。
｢Data loss｣→｢データ損失｣で統一するのはどうでしょうか?
データロストだと和製すぎるみたいです。名詞｢Data lost｣はあまりないようで。
Microsoftは｢データ損失｣と訳してるみたいです。
https://docs.microsoft.com/ja-jp/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention

2021-04-27 08:13 UTC, taksas commented on ja/Obsidian/Obsidianモバイル.md
> +下に示したように、Androidでの同期と同様のステップに従うことで同期できます。現在、Obsidian Syncによる同期とiCloudによる同期の両方を同時に使用することは推奨していません。同時使用によって競合状態によるデータロスの発生が報告されています。
確かに、そちらの方がよさそうだと思います。

2021-04-27 08:25 UTC, yo-goto commented
修正完了です

2021-04-27 08:44 UTC, taksas approved these changes
対応ありがとうございました!

2021-04-27 09:04 UTC, yo-goto commented
Review is finished. Ready to be merged.

2021-04-28 06:45 UTC, ericaxu commented
Thank you for your amazing work!

2021-04-28 06:45 UTC, merged